In [1]:
from numpy import *
import time
def trad_version ():
    t1 = time . time ()
    X = range (10000000)
    Y = range (10000000)
    Z = []
    for i in range (len (X)):
        Z. append (X[i] + Y[i])
    return time . time () - t1

In [2]:
trad_version()

7.371243000030518

In [3]:
def numpy_version ():
    t1 = time . time ()
    X = arange (10000000)
    Y = arange (10000000)
    Z = X + Y
    return time . time () - t1

In [4]:
numpy_version()

0.05584979057312012

In [5]:
import numpy as np
import warnings
warnings.filterwarnings("ignore")

In [6]:
list1 = [10, 20, 30, 40, 50, 60]
list1

[10, 20, 30, 40, 50, 60]

In [7]:
type(list1)

list

In [8]:
arr1 = np.array(list1)
arr1

array([10, 20, 30, 40, 50, 60])

In [9]:
arr1.data

In [10]:
type(arr1)

numpy.ndarray

In [11]:
arr1.dtype

dtype('int32')

In [12]:
arr1.astype(float)

array([10., 20., 30., 40., 50., 60.])

In [13]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
arr = np.array([1,2,3])
print(f'Numpy Array:{arr}')

mylist = arr.tolist()
print(f'List: {mylist}')

Numpy Array:[1 2 3]
List: [1, 2, 3]


In [15]:
np.arange(0, 100, 10)

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [16]:
np.arange(100, 0, -10)

array([100,  90,  80,  70,  60,  50,  40,  30,  20,  10])

In [17]:
arr3 = np.arange(0, 10)
arr3.shape

(10,)

In [18]:
arr3.dtype

dtype('int32')

In [19]:
arr3.nbytes

40

In [20]:
len(arr3)

10

In [21]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [22]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [23]:
np.repeat(10, 5)

array([10, 10, 10, 10, 10])

In [24]:
a = np.array([10,20,30])
np.repeat(a, 3)

array([10, 10, 10, 20, 20, 20, 30, 30, 30])

In [25]:
ar1 = np.arange(1, 20)
ar1[ar1 %2 == 1]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [26]:
ar1 = np.arange(1, 20)
ar1[ar1 %2 == 0]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [27]:
np.linspace(10, 20, 4)

array([10.        , 13.33333333, 16.66666667, 20.        ])

In [29]:
np.linspace(10, 20, 11)

array([10., 11., 12., 13., 14., 15., 16., 17., 18., 19., 20.])

In [30]:
np.random.random(4)

array([0.27051669, 0.07733409, 0.5815883 , 0.66287756])

In [31]:
np.random.randint(0, 500, 5)

array([ 81, 470, 412, 163, 371])

In [32]:
np.random.randint(0, 500, 10)

array([ 20, 337, 403, 181, 170,  33,  28,  76,   1, 364])

In [33]:
np.random.seed(123)
np.random.randint(0, 100, 10)

array([66, 92, 98, 17, 83, 57, 86, 97, 96, 47])

In [34]:
np.random.seed(123)
np.random.randint(0, 100, 10)

array([66, 92, 98, 17, 83, 57, 86, 97, 96, 47])

In [35]:
np.random.seed(101)
np.random.randint(0, 100, 10)

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [36]:
np.random.seed(101)
np.random.randint(0, 100, 10)

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [37]:
f1 = np.random.uniform(5, 10, size = (10))

In [38]:
f1

array([6.5348311 , 9.4680654 , 8.60771931, 5.94969477, 7.77113796,
       6.76065977, 5.90946201, 8.92800881, 9.82741611, 6.16176831])

In [39]:
np.floor(f1)

array([6., 9., 8., 5., 7., 6., 5., 8., 9., 6.])

In [40]:
np.trunc(f1)

array([6., 9., 8., 5., 7., 6., 5., 8., 9., 6.])

In [41]:
f1.astype(int)

array([6, 9, 8, 5, 7, 6, 5, 8, 9, 6])

In [44]:
f2 = np.random.uniform(5, 10, size = (10))
f2

array([7.60332698, 7.89394768, 8.67409529, 7.70980886, 9.56576779,
       9.03960075, 7.01498915, 6.78612171, 9.76438357, 6.71815789])

In [45]:
f2.astype(int)

array([7, 7, 8, 7, 9, 9, 7, 6, 9, 6])

In [46]:
b2 = np.random.randn(10)

In [47]:
b2

array([ 0.16690464,  0.18450186,  0.80770591,  0.07295968,  0.63878701,
        0.3296463 , -0.49710402, -0.7540697 , -0.9434064 ,  0.48475165])

In [48]:
arr1

array([10, 20, 30, 40, 50, 60])

In [49]:
for index, value in np.ndenumerate(arr1):
    print(index, value)

(0,) 10
(1,) 20
(2,) 30
(3,) 40
(4,) 50
(5,) 60


In [50]:
#Numpy dizileri üzerinde yapılan operasyonlar

In [51]:
arr2 = np.arange(1, 20)
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [52]:
arr2.sum()

190

In [53]:
np.cumsum(arr2)

array([  1,   3,   6,  10,  15,  21,  28,  36,  45,  55,  66,  78,  91,
       105, 120, 136, 153, 171, 190], dtype=int32)

In [54]:
#min, max, argmin, argmax, mean, var

In [55]:
np.std(arr2)

5.477225575051661

In [56]:
A = np.array([[1,2,3,0],[5,6,7,22],[10,11,1,13],[14,15,16,3]])
A

array([[ 1,  2,  3,  0],
       [ 5,  6,  7, 22],
       [10, 11,  1, 13],
       [14, 15, 16,  3]])

In [57]:
#sum, max, min, mean, var, std

In [58]:
np.amin(A, axis = 0) #sütun tabanlı minimum

array([1, 2, 1, 0])

In [59]:
np.amin(A, axis = 1) #satır tabanlı minimum

array([0, 5, 1, 3])

In [60]:
for index, value in np.ndenumerate(A):
    print(index, value)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 0
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 22
(2, 0) 10
(2, 1) 11
(2, 2) 1
(2, 3) 13
(3, 0) 14
(3, 1) 15
(3, 2) 16
(3, 3) 3
