In [1]:
import numpy as np

In [3]:
T1 = np.array([
    [[1,2,3], [4,5,6], [7,8,9]],
    [[10,20,30], [40,50,60], [70,80,90]],
    [[100,200,300], [400,500,600], [700,800,900]]
    ])
T1

array([[[  1,   2,   3],
        [  4,   5,   6],
        [  7,   8,   9]],

       [[ 10,  20,  30],
        [ 40,  50,  60],
        [ 70,  80,  90]],

       [[100, 200, 300],
        [400, 500, 600],
        [700, 800, 900]]])

In [4]:
T2 = np.array([
    [[0,0,0], [0,0,0], [0,0,0]],
    [[1,1,1], [1,1,1], [1,1,1]],
    [[2,2,2], [2,2,2], [2,2,2]]
    ])
T2

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[2, 2, 2],
        [2, 2, 2],
        [2, 2, 2]]])

In [5]:
A = T1 + T2
A
#OR
np.add(T1, T2)

array([[[  1,   2,   3],
        [  4,   5,   6],
        [  7,   8,   9]],

       [[ 11,  21,  31],
        [ 41,  51,  61],
        [ 71,  81,  91]],

       [[102, 202, 302],
        [402, 502, 602],
        [702, 802, 902]]])

In [6]:
S = T1 - T2
S
#OR
np.subtract(T1, T2)

array([[[  1,   2,   3],
        [  4,   5,   6],
        [  7,   8,   9]],

       [[  9,  19,  29],
        [ 39,  49,  59],
        [ 69,  79,  89]],

       [[ 98, 198, 298],
        [398, 498, 598],
        [698, 798, 898]]])

In [7]:
P = T1 * T2
P
#OR
np.multiply(T1, T2)

array([[[   0,    0,    0],
        [   0,    0,    0],
        [   0,    0,    0]],

       [[  10,   20,   30],
        [  40,   50,   60],
        [  70,   80,   90]],

       [[ 200,  400,  600],
        [ 800, 1000, 1200],
        [1400, 1600, 1800]]])

In [8]:
D = T1 / T2
D
#OR
np.divide(T1, T2)

<ipython-input-8-f02df7941bdf>:1: RuntimeWarning: divide by zero encountered in true_divide
  D = T1 / T2
<ipython-input-8-f02df7941bdf>:4: RuntimeWarning: divide by zero encountered in true_divide
  np.divide(T1, T2)


array([[[ inf,  inf,  inf],
        [ inf,  inf,  inf],
        [ inf,  inf,  inf]],

       [[ 10.,  20.,  30.],
        [ 40.,  50.,  60.],
        [ 70.,  80.,  90.]],

       [[ 50., 100., 150.],
        [200., 250., 300.],
        [350., 400., 450.]]])

In [14]:
myarray = np.where(np.isinf(D), 99, D)
myarray

array([[[ 99.,  99.,  99.],
        [ 99.,  99.,  99.],
        [ 99.,  99.,  99.]],

       [[ 10.,  20.,  30.],
        [ 40.,  50.,  60.],
        [ 70.,  80.,  90.]],

       [[ 50., 100., 150.],
        [200., 250., 300.],
        [350., 400., 450.]]])

In [15]:
import scipy as sp
#scipy.linalg, scipy.special, scipy.integrate, scipy.optimize, scipy.fftpack, scipy.signal, 
#scipy.stats, scipy.ndimage, scipy.io

In [16]:
from scipy import linalg
A = np.array([[1,2], [3,4]])
print(A)
B = linalg.inv(A)
print(B)

[[1 2]
 [3 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]


In [17]:
print(B.T)

[[-2.   1.5]
 [ 1.  -0.5]]


In [18]:
A = np.array([[1,3,5], [2,5,1], [2,3,8]])
print(A)
b = np.array([[10], [8], [3]])
print(b)
print("scipy-linalg ile denklem çözümü")
print(linalg.inv(A).dot(b))
print("np-solve ile denklem çözümü")
print(np.linalg.solve(A, b))

[[1 3 5]
 [2 5 1]
 [2 3 8]]
[[10]
 [ 8]
 [ 3]]
scipy-linalg ile denklem çözümü
[[-9.28]
 [ 5.16]
 [ 0.76]]
np-solve ile denklem çözümü
[[-9.28]
 [ 5.16]
 [ 0.76]]


In [19]:
from scipy import integrate
x2 = lambda x : x**2
I = integrate.quad(x2, 0, 6)
print(I)

(72.00000000000001, 7.993605777301129e-13)


In [21]:
#Bessel function
import scipy.special as special
result = integrate.quad(lambda x:special.jv(2.5, x), 0, 4.5)
print(result)

(1.1178179380783244, 7.866317216380707e-09)


In [22]:
from scipy.misc import derivative

In [23]:
def f(x):
    return x**3 + x**2
D = derivative(f, 1.0, dx = 1e-6)
print(D)

4.999999999921734


In [25]:
import pandas as pd
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings("ignore")

In [26]:
#Seriler

In [27]:
v = np.array([1,2,3,4,5,6,7])
s1 = pd.Series(v)
s1

0    1
1    2
2    3
3    4
4    5
5    6
6    7
dtype: int32

In [28]:
s1.nbytes

28

In [29]:
s1.count()

7

In [30]:
s1.size

7

In [31]:
s1.ndim

1

In [32]:
s0 = pd.Series([1,2,3], index = ['a', 'b', 'c'])
s0

a    1
b    2
c    3
dtype: int64

In [35]:
s1.index = ['a', 'b', 'c', 'd', 'e', 'f', 'g']
s1

a    1
b    2
c    3
d    4
e    5
f    6
g    7
dtype: int32

In [36]:
v2 = np.random.random(10)
ind2 = np.arange(0, 10)
s = pd.Series(v2, ind2)
v2, ind2, s

(array([0.72647714, 0.44556267, 0.3362042 , 0.62864172, 0.65894839,
        0.78108707, 0.78274764, 0.78414198, 0.74697424, 0.0847795 ]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 0    0.726477
 1    0.445563
 2    0.336204
 3    0.628642
 4    0.658948
 5    0.781087
 6    0.782748
 7    0.784142
 8    0.746974
 9    0.084780
 dtype: float64)

In [37]:
dict1 = {'a1':10, 'a2':20, 'a3':30, 'a4':40}
s3 = pd.Series(dict1)
s3

a1    10
a2    20
a3    30
a4    40
dtype: int64

In [38]:
pd.Series(99, index = [0,1,2,3,4,5])

0    99
1    99
2    99
3    99
4    99
5    99
dtype: int64

In [39]:
s

0    0.726477
1    0.445563
2    0.336204
3    0.628642
4    0.658948
5    0.781087
6    0.782748
7    0.784142
8    0.746974
9    0.084780
dtype: float64

In [40]:
s[:]

0    0.726477
1    0.445563
2    0.336204
3    0.628642
4    0.658948
5    0.781087
6    0.782748
7    0.784142
8    0.746974
9    0.084780
dtype: float64

In [41]:
s[0:3]

0    0.726477
1    0.445563
2    0.336204
dtype: float64

In [42]:
s[-1:]

9    0.08478
dtype: float64

In [43]:
s[:4]

0    0.726477
1    0.445563
2    0.336204
3    0.628642
dtype: float64

In [44]:
s[:-1]

0    0.726477
1    0.445563
2    0.336204
3    0.628642
4    0.658948
5    0.781087
6    0.782748
7    0.784142
8    0.746974
dtype: float64

In [45]:
s[-2:]

8    0.746974
9    0.084780
dtype: float64

In [46]:
s2 = s1.copy()
s2

a    1
b    2
c    3
d    4
e    5
f    6
g    7
dtype: int32

In [47]:
s3

a1    10
a2    20
a3    30
a4    40
dtype: int64

In [49]:
s4 = s2.append(s3)
s4

a      1
b      2
c      3
d      4
e      5
f      6
g      7
a1    10
a2    20
a3    30
a4    40
dtype: int64

In [50]:
s4.drop('a4', inplace = False)

a      1
b      2
c      3
d      4
e      5
f      6
g      7
a1    10
a2    20
a3    30
dtype: int64

In [51]:
s4

a      1
b      2
c      3
d      4
e      5
f      6
g      7
a1    10
a2    20
a3    30
a4    40
dtype: int64

In [52]:
s4.drop('a4', inplace = True)
s4

a      1
b      2
c      3
d      4
e      5
f      6
g      7
a1    10
a2    20
a3    30
dtype: int64

In [53]:
s4

a      1
b      2
c      3
d      4
e      5
f      6
g      7
a1    10
a2    20
a3    30
dtype: int64

In [54]:
s4 = s4.append(pd.Series({'a4':7}))
s4

a      1
b      2
c      3
d      4
e      5
f      6
g      7
a1    10
a2    20
a3    30
a4     7
dtype: int64

In [55]:
v1 = np.array([10, 20, 30])
v2 = np.array([1,2,3])
s1 = pd.Series(v1)
s2 = pd.Series(v2)
s1, s2

(0    10
 1    20
 2    30
 dtype: int32,
 0    1
 1    2
 2    3
 dtype: int32)

In [56]:
s1.add(s2)

0    11
1    22
2    33
dtype: int32

In [57]:
s1.sub(s2)

0     9
1    18
2    27
dtype: int32

In [58]:
s1.subtract(s2)

0     9
1    18
2    27
dtype: int32

In [59]:
s1.add(9)

0    19
1    29
2    39
dtype: int32

In [60]:
s1.mul(s2)

0    10
1    40
2    90
dtype: int32

In [61]:
s1.multiply(s2)

0    10
1    40
2    90
dtype: int32

In [62]:
s1.multiply(1000)

0    10000
1    20000
2    30000
dtype: int32

In [63]:
s1.divide(s2)

0    10.0
1    10.0
2    10.0
dtype: float64

In [64]:
s1.div(s2)

0    10.0
1    10.0
2    10.0
dtype: float64

In [65]:
#min(), max(), mean(), median(), std()

In [66]:
s1.equals(s2)

False

In [67]:
s5 = pd.Series([1,1,2,2,3,3],index=[0,1,2,3,4,5])
s5

0    1
1    1
2    2
3    2
4    3
5    3
dtype: int64

In [68]:
s5.value_counts()

1    2
2    2
3    2
dtype: int64

In [69]:
#DataFrames

In [70]:
df = pd.DataFrame()
df

Empty DataFrame
Columns: []
Index: []

In [71]:
lang = ['Java', 'Python', 'C', 'C++']
df = pd.DataFrame(lang)
df

0
0    Java
1  Python
2       C
3     C++

In [72]:
rating = [1,2,3,4]
df['kemal'] = rating
df

0  kemal
0    Java      1
1  Python      2
2       C      3
3     C++      4

In [73]:
scores = [100, 90, 80, 70]
df[1] = scores
df

0  kemal    1
0    Java      1  100
1  Python      2   90
2       C      3   80
3     C++      4   70

In [74]:
df.columns = ['Language', 'Rating', 'Scores']

In [75]:
df

Language  Rating  Scores
0     Java       1     100
1   Python       2      90
2        C       3      80
3      C++       4      70

In [76]:
data = [{'a':1, 'b':2}, {'a':5, 'b':10, 'c':20}]

df2 = pd.DataFrame(data)
df3 = pd.DataFrame(data, index = ['row1', 'row2'], columns = ['a','b'])
df4 = pd.DataFrame(data, index = ['row1', 'row2'], columns = ['a', 'b', 'c'])
df5 = pd.DataFrame(data, index = ['row1', 'row2'], columns = ['a', 'b', 'c', 'd'])

In [77]:
df2

a   b     c
0  1   2   NaN
1  5  10  20.0

In [78]:
df3

a   b
row1  1   2
row2  5  10

In [79]:
df4

a   b     c
row1  1   2   NaN
row2  5  10  20.0

In [80]:
df5

a   b     c   d
row1  1   2   NaN NaN
row2  5  10  20.0 NaN

In [81]:
dates = pd.date_range(start = '2022-09-16', end = '2022-09-22')
dates

DatetimeIndex(['2022-09-16', '2022-09-17', '2022-09-18', '2022-09-19',
               '2022-09-20', '2022-09-21', '2022-09-22'],
              dtype='datetime64[ns]', freq='D')

In [82]:
dates = pd.date_range('today', periods = 7)

In [83]:
dates

DatetimeIndex(['2022-09-16 22:37:20.309354', '2022-09-17 22:37:20.309354',
               '2022-09-18 22:37:20.309354', '2022-09-19 22:37:20.309354',
               '2022-09-20 22:37:20.309354', '2022-09-21 22:37:20.309354',
               '2022-09-22 22:37:20.309354'],
              dtype='datetime64[ns]', freq='D')

In [84]:
dates = pd.date_range(start = '2022-09-16', periods = 7)

In [85]:
dates

DatetimeIndex(['2022-09-16', '2022-09-17', '2022-09-18', '2022-09-19',
               '2022-09-20', '2022-09-21', '2022-09-22'],
              dtype='datetime64[ns]', freq='D')

In [86]:
M = np.random.random((7,7))
M

array([[0.35500195, 0.92974109, 0.68774998, 0.21741458, 0.13679432,
        0.85223941, 0.91099041],
       [0.26436313, 0.8691829 , 0.31108272, 0.9637203 , 0.04485804,
        0.62017385, 0.35182066],
       [0.6228924 , 0.43453706, 0.2678102 , 0.41078379, 0.55193965,
        0.45223185, 0.05820521],
       [0.01938575, 0.99465671, 0.89243955, 0.33082039, 0.35279951,
        0.89261794, 0.77302384],
       [0.4441238 , 0.5509972 , 0.92519025, 0.78061661, 0.12300066,
        0.23322539, 0.28811696],
       [0.79987064, 0.66533919, 0.34752877, 0.27731671, 0.42062222,
        0.12254124, 0.21216193],
       [0.73171164, 0.49881071, 0.90072149, 0.02318179, 0.5251782 ,
        0.11075644, 0.89666465]])

In [87]:
dframe = pd.DataFrame(M, index = dates)
dframe

0         1         2         3         4         5  \
2022-09-16  0.355002  0.929741  0.687750  0.217415  0.136794  0.852239   
2022-09-17  0.264363  0.869183  0.311083  0.963720  0.044858  0.620174   
2022-09-18  0.622892  0.434537  0.267810  0.410784  0.551940  0.452232   
2022-09-19  0.019386  0.994657  0.892440  0.330820  0.352800  0.892618   
2022-09-20  0.444124  0.550997  0.925190  0.780617  0.123001  0.233225   
2022-09-21  0.799871  0.665339  0.347529  0.277317  0.420622  0.122541   
2022-09-22  0.731712  0.498811  0.900721  0.023182  0.525178  0.110756   

                   6  
2022-09-16  0.910990  
2022-09-17  0.351821  
2022-09-18  0.058205  
2022-09-19  0.773024  
2022-09-20  0.288117  
2022-09-21  0.212162  
2022-09-22  0.896665

In [88]:
dframe.columns = ['C1', 'C2', 'C3', 'C4', 'C5', 'C6', 'C7']
dframe

C1        C2        C3        C4        C5        C6  \
2022-09-16  0.355002  0.929741  0.687750  0.217415  0.136794  0.852239   
2022-09-17  0.264363  0.869183  0.311083  0.963720  0.044858  0.620174   
2022-09-18  0.622892  0.434537  0.267810  0.410784  0.551940  0.452232   
2022-09-19  0.019386  0.994657  0.892440  0.330820  0.352800  0.892618   
2022-09-20  0.444124  0.550997  0.925190  0.780617  0.123001  0.233225   
2022-09-21  0.799871  0.665339  0.347529  0.277317  0.420622  0.122541   
2022-09-22  0.731712  0.498811  0.900721  0.023182  0.525178  0.110756   

                  C7  
2022-09-16  0.910990  
2022-09-17  0.351821  
2022-09-18  0.058205  
2022-09-19  0.773024  
2022-09-20  0.288117  
2022-09-21  0.212162  
2022-09-22  0.896665

In [89]:
dframe.index

DatetimeIndex(['2022-09-16', '2022-09-17', '2022-09-18', '2022-09-19',
               '2022-09-20', '2022-09-21', '2022-09-22'],
              dtype='datetime64[ns]', freq='D')

In [90]:
dframe.columns

Index(['C1', 'C2', 'C3', 'C4', 'C5', 'C6', 'C7'], dtype='object')

In [91]:
dframe.dtypes

C1    float64
C2    float64
C3    float64
C4    float64
C5    float64
C6    float64
C7    float64
dtype: object

In [92]:
dframe.sort_values(by = 'C1') #ascending

C1        C2        C3        C4        C5        C6  \
2022-09-19  0.019386  0.994657  0.892440  0.330820  0.352800  0.892618   
2022-09-17  0.264363  0.869183  0.311083  0.963720  0.044858  0.620174   
2022-09-16  0.355002  0.929741  0.687750  0.217415  0.136794  0.852239   
2022-09-20  0.444124  0.550997  0.925190  0.780617  0.123001  0.233225   
2022-09-18  0.622892  0.434537  0.267810  0.410784  0.551940  0.452232   
2022-09-22  0.731712  0.498811  0.900721  0.023182  0.525178  0.110756   
2022-09-21  0.799871  0.665339  0.347529  0.277317  0.420622  0.122541   

                  C7  
2022-09-19  0.773024  
2022-09-17  0.351821  
2022-09-16  0.910990  
2022-09-20  0.288117  
2022-09-18  0.058205  
2022-09-22  0.896665  
2022-09-21  0.212162

In [93]:
dframe.sort_values(by = 'C1', ascending = False)

C1        C2        C3        C4        C5        C6  \
2022-09-21  0.799871  0.665339  0.347529  0.277317  0.420622  0.122541   
2022-09-22  0.731712  0.498811  0.900721  0.023182  0.525178  0.110756   
2022-09-18  0.622892  0.434537  0.267810  0.410784  0.551940  0.452232   
2022-09-20  0.444124  0.550997  0.925190  0.780617  0.123001  0.233225   
2022-09-16  0.355002  0.929741  0.687750  0.217415  0.136794  0.852239   
2022-09-17  0.264363  0.869183  0.311083  0.963720  0.044858  0.620174   
2022-09-19  0.019386  0.994657  0.892440  0.330820  0.352800  0.892618   

                  C7  
2022-09-21  0.212162  
2022-09-22  0.896665  
2022-09-18  0.058205  
2022-09-20  0.288117  
2022-09-16  0.910990  
2022-09-17  0.351821  
2022-09-19  0.773024

In [94]:
df1

NameError: name 'df1' is not defined

In [95]:
df2

a   b     c
0  1   2   NaN
1  5  10  20.0

In [96]:
df5

a   b     c   d
row1  1   2   NaN NaN
row2  5  10  20.0 NaN

In [97]:
del df5['d']

In [98]:
df5

a   b     c
row1  1   2   NaN
row2  5  10  20.0

In [99]:
df5.pop('c')

row1     NaN
row2    20.0
Name: c, dtype: float64

In [100]:
df5

a   b
row1  1   2
row2  5  10

In [101]:
df5.drop(['b'], axis = 1, inplace = True)
df5

a
row1  1
row2  5

In [ ]:
#Pandas Satır Silme